In [120]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

#from workflows import workflow

In [121]:
df=pd.read_csv("netflix.csv")

In [122]:
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

In [123]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

**Renaming the listed in column to genres**

In [124]:
df.rename(columns={'listed_in':'genre'}, inplace=True)
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'genre', 'description'],
      dtype='str')

**Dropping the show_id column as it may be of no use in the analysis**

In [125]:
df.drop(columns='show_id', inplace=True)

In [126]:
# identical rows----means by mistake you enter same data for so many time it also can degrade
# the performace of analysis.

In [127]:
s1='179 min'
int(s1.split()[0])

179

In [128]:
s1='12 Seasons'
int(s1.split()[0])

12

In [129]:
#df["duration"]=df["duration"].apply(lambda x:int(x.split()[0]))

In [130]:
df["duration"].unique()

<StringArray>
[   '90 min', '2 Seasons',  '1 Season',    '91 min',   '125 min', '9 Seasons',
   '104 min',   '127 min', '4 Seasons',    '67 min',
 ...
    '43 min',   '200 min',   '196 min',   '167 min',   '178 min',   '228 min',
    '18 min',   '205 min',   '201 min',   '191 min']
Length: 221, dtype: str

In [131]:
df["rating"].unique()

<StringArray>
[   'PG-13',    'TV-MA',       'PG',    'TV-14',    'TV-PG',     'TV-Y',
    'TV-Y7',        'R',     'TV-G',        'G',    'NC-17',   '74 min',
   '84 min',   '66 min',       'NR',        nan, 'TV-Y7-FV',       'UR']
Length: 18, dtype: str

In [132]:
df['rating']=df['rating'].replace(['TV-Y','TY-Y7','G','TV-G','TV-PG','TV-Y7-FV'],'Kids')
df['rating']=df['rating'].replace(['PG-13','TV-14'],'Teens')
df['rating']=df['rating'].replace(['R','TV-MA','NC-17'],'Adults')
df['rating']=df['rating'].replace(['NR','UR'],'np.nan')
df.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,genre,description
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,Teens,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,Adults,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,Adults,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,Adults,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,Adults,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [133]:
df.dropna(subset=['rating'],inplace=True)
df['rating'].isna().sum()

np.int64(0)

**82 value were null,which was only about 1% of data,so we deleted those rows.**

In [134]:
df.isna().sum()

type               0
title              0
director        2631
cast             825
country          830
date_added        10
release_year       0
rating             0
duration           3
genre              0
description        0
dtype: int64

**NOW, we still about 48% missing data. So, we will check in which rows the director, country use of that rows.**

In [135]:
df[
    (df['director'].isna()) &
    (df['country'].isna()) &
    (df['cast'].isna())
].shape[0]

96

In [136]:
df.shape

(8803, 11)

In [137]:
df.dropna(subset=['director','country','cast'], how='all', inplace=True)

In [138]:
df["cast"][2]

'Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera'

In [139]:
df_cast = pd.DataFrame(df["cast"].apply(lambda x: str(x).split(", ")).tolist(),index=df['title'])

In [140]:
df_cast

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
title,,,,,,,,,,,,,,,,,,,,,
Dick Johnson Is Dead,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Blood & Water,Ama Qamata,Khosi Ngema,Gail Mabalane,Thabang Molaba,Dillon Windvogel,Natasha Thahane,Arno Greeff,Xolile Tshabalala,Getmore Sithole,Cindy Mahlangu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ganglands,Sami Bouajila,Tracy Gotoas,Samuel Jouy,Nabiha Akkari,Sofia Lesaffre,Salim Kechiouche,Noureddine Farihi,Geert Van Rampelberg,Bakary Diombera,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kota Factory,Mayur More,Jitendra Kumar,Ranjan Raj,Alam Khan,Ahsaas Channa,Revathi Pillai,Urvi Singh,Arun Kumar,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Midnight Mass,Kate Siegel,Zach Gilford,Hamish Linklater,Henry Thomas,Kristin Lehman,Samantha Sloyan,Igby Rigney,Rahul Kohli,Annarah Cymone,Annabeth Gish,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zinzana,Ali Suliman,Saleh Bakri,Yasa,Ali Al-Jabri,Mansoor Alfeeli,Ahd,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zodiac,Mark Ruffalo,Jake Gyllenhaal,Robert Downey Jr.,Anthony Edwards,Brian Cox,Elias Koteas,Donal Logue,John Carroll Lynch,Dermot Mulroney,Chloë Sevigny,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zombieland,Jesse Eisenberg,Woody Harrelson,Emma Stone,Abigail Breslin,Amber Heard,Bill Murray,Derek Graf,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zoom,Tim Allen,Courteney Cox,Chevy Chase,Kate Mara,Ryan Newman,Michael Cassidy,Spencer Breslin,Rip Torn,Kevin Zegers,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zubaan,Vicky Kaushal,Sarah-Jane Dias,Raaghav Chanana,Manish Chaudhary,Meghna Malik,Malkeet Rauni,Anita Shabdish,Chittaranjan Tripathy,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [141]:
df_cast = df_cast.stack()
df_cast

title
Dick Johnson Is Dead  0     nan
                      1     NaN
                      2     NaN
                      3     NaN
                      4     NaN
                           ...
Zubaan                45    NaN
                      46    NaN
                      47    NaN
                      48    NaN
                      49    NaN
Length: 435350, dtype: str

In [142]:
df_cast=pd.DataFrame(df_cast)
df_cast

                           0
title
Dick Johnson Is Dead 0   nan
                     1   NaN
                     2   NaN
                     3   NaN
                     4   NaN
...                      ...
Zubaan               45  NaN
                     46  NaN
                     47  NaN
                     48  NaN
                     49  NaN

[435350 rows x 1 columns]

In [143]:
df_cast = df_cast.reset_index()[['title', 0]]
df_cast

                       title    0
0       Dick Johnson Is Dead  nan
1       Dick Johnson Is Dead  NaN
2       Dick Johnson Is Dead  NaN
3       Dick Johnson Is Dead  NaN
4       Dick Johnson Is Dead  NaN
...                      ...  ...
435345                Zubaan  NaN
435346                Zubaan  NaN
435347                Zubaan  NaN
435348                Zubaan  NaN
435349                Zubaan  NaN

[435350 rows x 2 columns]

In [144]:
df_cast.columns=['title','cast']
df_cast

                       title cast
0       Dick Johnson Is Dead  nan
1       Dick Johnson Is Dead  NaN
2       Dick Johnson Is Dead  NaN
3       Dick Johnson Is Dead  NaN
4       Dick Johnson Is Dead  NaN
...                      ...  ...
435345                Zubaan  NaN
435346                Zubaan  NaN
435347                Zubaan  NaN
435348                Zubaan  NaN
435349                Zubaan  NaN

[435350 rows x 2 columns]

In [145]:
df_cast.replace('nan',np.nan, inplace=True)
df_cast.isna().sum()

title         0
cast     371262
dtype: int64

**Now we will split all the nested data individually and save them in a new dataframe, and then we will merge all of the**

In [146]:
df_genre = pd.DataFrame(df["genre"].apply(lambda x: str(x).split(", ")).tolist(),index=df['title'])
df_genre = df_genre.stack()
df_genre=pd.DataFrame(df_genre)
df_genre.reset_index(inplace=True)
df_genre = df_genre[['title', 0]]
df_genre.columns=['title','genre']
df_genre.replace('nan',np.nan, inplace=True)
df_genre.isna().sum()

title       0
genre    6988
dtype: int64

In [147]:
df.columns

Index(['type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'genre', 'description'],
      dtype='str')

In [148]:
df_country = pd.DataFrame(df["country"].apply(lambda x: str(x).split(", ")).tolist(),index=df['title'])
df_country = df_country.stack()
df_country=pd.DataFrame(df_country)
df_country.reset_index(inplace=True)
df_country = df_country[['title', 0]]
df_country.columns=['title','country']
df_country.replace('nan',np.nan, inplace=True)
df_country.isna().sum()

title          0
country    94473
dtype: int64

In [149]:
df12 = df_cast.merge(df_genre, on='title')
df12

                        title cast                 genre
0        Dick Johnson Is Dead  NaN         Documentaries
1        Dick Johnson Is Dead  NaN                   NaN
2        Dick Johnson Is Dead  NaN                   NaN
3        Dick Johnson Is Dead  NaN         Documentaries
4        Dick Johnson Is Dead  NaN                   NaN
...                       ...  ...                   ...
1306045                Zubaan  NaN  International Movies
1306046                Zubaan  NaN      Music & Musicals
1306047                Zubaan  NaN                Dramas
1306048                Zubaan  NaN  International Movies
1306049                Zubaan  NaN      Music & Musicals

[1306050 rows x 3 columns]

In [150]:
df123 = df_director.merge(df12, on='title')
df123

NameError: name 'df_director' is not defined

In [ ]:
df1234 = df_country.merge(df123, on='title')
df1234

NameError: name 'df123' is not defined

In [151]:
df_new =df,merge(df1234, on='title')
df_new

NameError: name 'merge' is not defined

In [ ]:
df_new.drop(columns='cast_x','country_x',)