In [15]:
import pandas as pd

In [28]:
import numpy as np

In [16]:
df=pd.read_csv("replace_data.csv")

In [17]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [22]:
df=pd.read_csv("replace_data1_1.csv")

In [19]:
df=pd.read_csv("replace_data1.csv")

In [20]:
df=pd.read_csv("replace_data2.csv")

In [33]:
new_df = df.replace(-99999, value=np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [31]:
new_df = df.replace([-99999, -88888,'no event'],np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [25]:
df=pd.read_csv("replace_data.csv")

In [30]:
new_df=df.replace({'temperature': -99999,'windspeed': -88888,'event': 'no event'},np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0          6   Rain
1  1/2/2017          NaN          7  Sunny
2  1/3/2017         28.0     -99999   Snow
3  1/4/2017          NaN          7      0
4  1/5/2017         32.0     -99999   Rain
5  1/6/2017         31.0          2  Sunny
6  1/6/2017         34.0          5      0

In [34]:
df=pd.read_csv("replace_data1.csv")

In [35]:
new_df=df.replace({-99999 : np.nan,'no event':'Sunny'})

In [36]:
new_df

          day  temperature  windspeed  event
0  01-01-2017         32.0        6.0   Rain
1  01-02-2017          NaN        7.0  Sunny
2  01-03-2017         28.0        NaN   Snow
3  01-04-2017          NaN        7.0  Sunny
4  01-05-2017         32.0        NaN   Rain
5  01-06-2017         31.0        2.0  Sunny
6  01-06-2017         34.0        5.0  Sunny