In [17]:
import plotly.express as px
import pandas as pd

In [18]:
d1 = px.data.gapminder()
d1.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [19]:
data_canada=d1[d1["country"]=="Canada"]

In [20]:
px.bar(data_canada,x="year",y="pop",text="year",color="year")

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'year=%{marker.color}<br>pop=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': {'bdata': 'oAelB6oHrwe0B7kHvgfDB8gHzQfSB9cH', 'dtype': 'i2'},
                         'coloraxis': 'coloraxis',
                         'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'text': {'bdata': ('AAAAAACAnkAAAAAAAJSeQAAAAAAAqJ' ... 'AAAAA0n0AAAAAAAEifQAAAAAAAXJ9A'),
                       'dtype': 'f8'},
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'oAelB6oHrwe0B7kHvgfDB8gHzQfSB9cH', 'dtype': 'i2'},
              'xaxis': 'x',
              'y': {'bdata': 'MJzhAOqNAwF5syEBN689AdQIVAGwGmsB7IyAAcQdlQHuO7MBM27OATzK5gE9fv0B', 'dtype': 'i4'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'coloraxis': {'colorbar': {'title': {'text': 'year'}},
                             'colorscale': [[0.0, '#0d0887'], [0.1111111111111111,
                                            '#46039f'], [0.2222222222222222,
                                            '#7201a8'], [0.3333333333333333,
                                            '#9c179e'], [0.4444444444444444,
                                            '#bd3786'], [0.5555555555555556,
                                            '#d8576b'], [0.6666666666666666,
                                            '#ed7953'], [0.7777777777777778,
                                            '#fb9f3a'], [0.8888888888888888,
                                            '#fdca26'], [1.0, '#f0f921']]},
               'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'year'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'pop'}}}
})

In [21]:
px.bar(data_canada,x="year",y="pop",
       hover_data=["lifeExp","gdpPercap"],labels={'pop':'population of canada'},
       height=400,text='year',color='year')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'customdata': {'bdata': ('AAAAAAAwUUBehZSflDPGQD0K16NwfV' ... 'va4R5G4EBvEoPAyilUQAexM4Xnu+FA'),
                             'dtype': 'f8',
                             'shape': '12, 2'},
              'hovertemplate': ('year=%{marker.color}<br>popula' ... '{customdata[1]}<extra></extra>'),
              'legendgroup': '',
              'marker': {'color': {'bdata': 'oAelB6oHrwe0B7kHvgfDB8gHzQfSB9cH', 'dtype': 'i2'},
                         'coloraxis': 'coloraxis',
                         'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'text': {'bdata': ('AAAAAACAnkAAAAAAAJSeQAAAAAAAqJ' ... 'AAAAA0n0AAAAAAAEifQAAAAAAAXJ9A'),
                       'dtype': 'f8'},
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'oAelB6oHrwe0B7kHvgfDB8gHzQfSB9cH', 'dtype': 'i2'},
              'xaxis': 'x',
              'y': {'bdata': 'MJzhAOqNAwF5syEBN689AdQIVAGwGmsB7IyAAcQdlQHuO7MBM27OATzK5gE9fv0B', 'dtype': 'i4'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'coloraxis': {'colorbar': {'title': {'text': 'year'}},
                             'colorscale': [[0.0, '#0d0887'], [0.1111111111111111,
                                            '#46039f'], [0.2222222222222222,
                                            '#7201a8'], [0.3333333333333333,
                                            '#9c179e'], [0.4444444444444444,
                                            '#bd3786'], [0.5555555555555556,
                                            '#d8576b'], [0.6666666666666666,
                                            '#ed7953'], [0.7777777777777778,
                                            '#fb9f3a'], [0.8888888888888888,
                                            '#fdca26'], [1.0, '#f0f921']]},
               'height': 400,
               'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'year'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'population of canada'}}}
})

In [22]:
wide_data=px.data.medals_long()

In [23]:
wide_data.head()

        nation   medal  count
0  South Korea    gold     24
1        China    gold     10
2       Canada    gold      9
3  South Korea  silver     13
4        China  silver     15

In [24]:
px.bar(wide_data,x="nation",y="count",color="medal")

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'medal=gold<br>nation=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'gold',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': 'gold',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['South Korea', 'China', 'Canada'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'GAoJ', 'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': 'medal=silver<br>nation=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'silver',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': 'silver',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['South Korea', 'China', 'Canada'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'DQ8M', 'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': 'medal=bronze<br>nation=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'bronze',
              'marker': {'color': '#00cc96', 'pattern': {'shape': ''}},
              'name': 'bronze',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['South Korea', 'China', 'Canada'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'CwgM', 'dtype': 'i1'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'medal'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'nation'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [25]:
px.line(data_canada,x="year",y="lifeExp",title="Life Exp in canada",markers=True)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'year=%{x}<br>lifeExp=%{y}<extra></extra>',
              'legendgroup': '',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines+markers',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': {'bdata': 'oAelB6oHrwe0B7kHvgfDB8gHzQfSB9cH', 'dtype': 'i2'},
              'xaxis': 'x',
              'y': {'bdata': ('AAAAAAAwUUA9CtejcH1RQDMzMzMz01' ... 'NwPQqnU0DhehSuR/FTQG8Sg8DKKVRA'),
                    'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Life Exp in canada'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'year'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'lifeExp'}}}
})