# Concat and Merge

In [5]:
import pandas as pd

In [7]:
df1 = pd.DataFrame({'Name': ['Vicky', 'Bill'], 'Age': [12, 46]})
df2=pd.DataFrame({'Name':['John','Sabrina'],'Age':[37,25]})
df1

    Name  Age
0  Vicky   12
1   Bill   46

In [8]:
df2

      Name  Age
0     John   37
1  Sabrina   25

In [9]:
cars=pd.concat([df1,df2],axis=1)
cars

    Name  Age     Name  Age
0  Vicky   12     John   37
1   Bill   46  Sabrina   25

In [13]:
cars=pd.concat([df1,df2],axis=0,ignore_index=True)
cars

      Name  Age
0    Vicky   12
1     Bill   46
2     John   37
3  Sabrina   25

In [16]:
df3=pd.concat([df1,df2],axis=0,ignore_index=True)
df3

      Name  Age
0    Vicky   12
1     Bill   46
2     John   37
3  Sabrina   25

In [14]:
df4=pd.DataFrame({'Name':['Tyler','Natalie'],'Age':[28,39],
                  'Hobby':['Swimming','Reading']})

In [15]:
df4

      Name  Age     Hobby
0    Tyler   28  Swimming
1  Natalie   39   Reading

In [17]:
pd.concat([df3,df4],join='inner',ignore_index=True)

      Name  Age
0    Vicky   12
1     Bill   46
2     John   37
3  Sabrina   25
4    Tyler   28
5  Natalie   39

In [18]:
pd.concat([df3,df4],join='outer',ignore_index=True)

      Name  Age     Hobby
0    Vicky   12       NaN
1     Bill   46       NaN
2     John   37       NaN
3  Sabrina   25       NaN
4    Tyler   28  Swimming
5  Natalie   39   Reading

In [19]:
size=pd.DataFrame({'Colour':['Red','Blue','Green'],'Size':['M','S','M']})
gender=pd.DataFrame({'Colour':['Red','Blue','Yellow'],'Sex':['Female','Female','Male']})
size

  Colour Size
0    Red    M
1   Blue    S
2  Green    M

In [20]:
gender

   Colour     Sex
0     Red  Female
1    Blue  Female
2  Yellow    Male

In [21]:
pd.merge(size,gender,how = 'inner')

  Colour Size     Sex
0    Red    M  Female
1   Blue    S  Female

In [22]:
pd.merge(size,gender,how = 'outer')

   Colour Size     Sex
0    Blue    S  Female
1   Green    M     NaN
2     Red    M  Female
3  Yellow  NaN    Male

In [23]:
pd.merge(size,gender,how = 'left')

  Colour Size     Sex
0    Red    M  Female
1   Blue    S  Female
2  Green    M     NaN

In [24]:
pd.merge(size,gender,how = 'right')

   Colour Size     Sex
0     Red    M  Female
1    Blue    S  Female
2  Yellow  NaN    Male

In [29]:
pd.merge(size,gender,how = 'cross')

  Colour_x Size Colour_y     Sex
0      Red    M      Red  Female
1      Red    M     Blue  Female
2      Red    M   Yellow    Male
3     Blue    S      Red  Female
4     Blue    S     Blue  Female
5     Blue    S   Yellow    Male
6    Green    M      Red  Female
7    Green    M     Blue  Female
8    Green    M   Yellow    Male