In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("employee.csv")

In [4]:
# Univariate Analysis
# Bivariate Analysis 
# Multivariate Analysis

In [5]:
# Univariate Analysis 
# You Can do this with text columns as value_counts()
# You can do this with numerical columnn as mean,median,mode

In [7]:
df["Department"].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [8]:
df["BusinessTravel"].value_counts()

BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

In [9]:
df["Gender"].value_counts()

Gender
Male      882
Female    588
Name: count, dtype: int64

In [13]:
df["EducationField"].value_counts()

EducationField
Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: count, dtype: int64

In [14]:
# Bivariate Analysis
# df.groupby(categorical)[numerical].mean(),median,max,min

In [17]:
# What is the average age of employees in each department

df.groupby("Gender")["Age"].mean()

Gender
Female    37.329932
Male      36.653061
Name: Age, dtype: float64

In [21]:
# What is the average MonthlyIncome of employees in each department

df.groupby("Department")["MonthlyIncome"].mean()

Department
Human Resources           6654.507937
Research & Development    6281.252862
Sales                     6959.172646
Name: MonthlyIncome, dtype: float64

In [22]:
# What is the average MontlyIncome of employees from each EductationField

df.groupby("EducationField")["MonthlyIncome"].mean()

EducationField
Human Resources     7241.148148
Life Sciences       6463.288779
Marketing           7348.584906
Medical             6510.036638
Other               6071.548780
Technical Degree    5758.303030
Name: MonthlyIncome, dtype: float64

In [23]:
# Count how many male and female are in each department 

df.groupby("Department")["Gender"].value_counts()

Department              Gender
Human Resources         Male       43
                        Female     20
Research & Development  Male      582
                        Female    379
Sales                   Male      257
                        Female    189
Name: count, dtype: int64

In [27]:
# Multivariate Analysis 
# What is the average Age of employees in each department and educationfield

df.groupby(["Department","EducationField"])["Age"].mean()

Department              EducationField
Human Resources         Human Resources     37.037037
                        Life Sciences       39.375000
                        Medical             39.846154
                        Other               34.666667
                        Technical Degree    32.500000
Research & Development  Life Sciences       36.997727
                        Medical             37.242424
                        Other               36.187500
                        Technical Degree    37.063830
Sales                   Life Sciences       37.186667
                        Marketing           37.924528
                        Medical             34.727273
                        Other               32.000000
                        Technical Degree    33.941176
Name: Age, dtype: float64

In [28]:
df.groupby(["Department","EducationField"])["MonthlyIncome"].mean()

Department              EducationField
Human Resources         Human Resources     7241.148148
                        Life Sciences       6914.062500
                        Medical             6594.076923
                        Other               5016.666667
                        Technical Degree    3081.250000
Research & Development  Life Sciences       6179.984091
                        Medical             6539.223140
                        Other               6278.687500
                        Technical Degree    5760.819149
Sales                   Life Sciences       7246.233333
                        Marketing           7348.584906
                        Medical             6377.227273
                        Other               5398.733333
                        Technical Degree    6066.294118
Name: MonthlyIncome, dtype: float64

In [29]:
df.groupby("Department")[["Age","MonthlyIncome"]].mean()

                              Age  MonthlyIncome
Department
Human Resources         37.809524    6654.507937
Research & Development  37.042664    6281.252862
Sales                   36.542601    6959.172646

In [30]:
df.groupby(["Department","EducationField"])[["Age","MonthlyIncome"]].mean()

                                               Age  MonthlyIncome
Department             EducationField
Human Resources        Human Resources   37.037037    7241.148148
                       Life Sciences     39.375000    6914.062500
                       Medical           39.846154    6594.076923
                       Other             34.666667    5016.666667
                       Technical Degree  32.500000    3081.250000
Research & Development Life Sciences     36.997727    6179.984091
                       Medical           37.242424    6539.223140
                       Other             36.187500    6278.687500
                       Technical Degree  37.063830    5760.819149
Sales                  Life Sciences     37.186667    7246.233333
                       Marketing         37.924528    7348.584906
                       Medical           34.727273    6377.227273
                       Other             32.000000    5398.733333
                       Technical Degree  33.941176    6066.294118

In [31]:
df.groupby("Department")["Age"].agg(["mean","max","min","median"])

                             mean  max  min  median
Department
Human Resources         37.809524   59   19    37.0
Research & Development  37.042664   60   18    36.0
Sales                   36.542601   60   18    35.0

In [32]:
df.groupby(["Department","EducationField"])[["Age","MonthlyIncome"]].agg(["mean","max","min","median"])

                                               Age                 \
                                              mean max min median
Department             EducationField
Human Resources        Human Resources   37.037037  59  24   36.0
                       Life Sciences     39.375000  56  26   41.0
                       Medical           39.846154  59  24   42.0
                       Other             34.666667  38  29   37.0
                       Technical Degree  32.500000  42  19   34.5
Research & Development Life Sciences     36.997727  60  18   36.0
                       Medical           37.242424  60  18   36.0
                       Other             36.187500  53  21   35.5
                       Technical Degree  37.063830  58  20   35.5
Sales                  Life Sciences     37.186667  59  20   36.0
                       Marketing         37.924528  60  18   36.0
                       Medical           34.727273  58  18   34.0
                       Other             32.000000  50  19   31.0
                       Technical Degree  33.941176  59  19   33.0

                                        MonthlyIncome
                                                 mean    max   min  median
Department             EducationField
Human Resources        Human Resources    7241.148148  19636  1555  3886.0
                       Life Sciences      6914.062500  19717  2064  4014.5
                       Medical            6594.076923  18200  2109  4936.0
                       Other              5016.666667   7988  2991  4071.0
                       Technical Degree   3081.250000   4323  2564  2719.0
Research & Development Life Sciences      6179.984091  19999  1051  4394.0
                       Medical            6539.223140  19859  1009  4422.0
                       Other              6278.687500  19613  1951  4045.5
                       Technical Degree   5760.819149  19943  1274  3990.5
Sales                  Life Sciences      7246.233333  19847  1118  6146.0
                       Marketing          7348.584906  19845  1675  6118.0
                       Medical            6377.227273  19833  1052  5466.5
                       Other              5398.733333  10932  2121  4805.0
                       Technical Degree   6066.294118  16872  1091  5669.5

In [34]:
pd.pivot_table(index=["Department","EducationField"],values="MonthlyIncome",data=df,aggfunc="mean")

                                         MonthlyIncome
Department             EducationField
Human Resources        Human Resources     7241.148148
                       Life Sciences       6914.062500
                       Medical             6594.076923
                       Other               5016.666667
                       Technical Degree    3081.250000
Research & Development Life Sciences       6179.984091
                       Medical             6539.223140
                       Other               6278.687500
                       Technical Degree    5760.819149
Sales                  Life Sciences       7246.233333
                       Marketing           7348.584906
                       Medical             6377.227273
                       Other               5398.733333
                       Technical Degree    6066.294118

# Missing Value Imputation

In [59]:
import pandas as pd

In [60]:
df=pd.read_csv("train.csv")

In [61]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [62]:
df.isnull().sum().sum()

np.int64(7829)

In [63]:
# What can we do if we have null values 
# 1. Drop the rows or columns having null values
# 2. Fill The empty cells with some value

In [64]:
# Drop the rows

df.dropna() # Complete data loss

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice]
Index: []

[0 rows x 81 columns]

In [65]:
df.dropna(axis=1) # Column loss

,Id,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,7917,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,13175,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,9042,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,9717,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,9937,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [66]:
# Fill null values 
# First you have to check the data type of the column you want to fill
# if data type is numerical that you can fill that with mean or median 
# if data type is categorical then you can fill with mode or custom value

In [67]:
df["LotFrontage"].isnull().sum()

np.int64(259)

In [68]:
df["LotFrontage"].dtype

dtype('float64')

In [69]:
df["LotFrontage"].agg(["mean","median"])

mean      70.049958
median    69.000000
Name: LotFrontage, dtype: float64

In [70]:
df["LotFrontage"].fillna(df["LotFrontage"].median(),inplace=True)

C:\Users\PARAS\AppData\Local\Temp\ipykernel_24484\2114410857.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["LotFrontage"].fillna(df["LotFrontage"].median(),inplace=True)

0       65.0
1       80.0
2       68.0
3       60.0
4       84.0
        ...
1455    62.0
1456    85.0
1457    66.0
1458    68.0
1459    75.0
Name: LotFrontage, Length: 1460, dtype: float64

In [71]:
df[df["LotFrontage"]==69]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
71,72,20,RL,69.0,7599,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,129500
94,95,60,RL,69.0,9337,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,204750
128,129,60,RL,69.0,7590,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,155000
129,130,20,RL,69.0,8973,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnWw,NaN,0,7,2006,WD,Abnorml,150000
246,247,190,RM,69.0,9142,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,137000
261,262,60,RL,69.0,9588,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,New,Partial,276000
397,398,60,RL,69.0,7590,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2007,WD,Normal,169500
556,557,20,RL,69.0,14850,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnWw,NaN,0,5,2006,WD,Normal,141000
595,596,20,RL,69.0,11302,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2006,New,Partial,319000
719,720,20,RL,69.0,9920,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,128500
1214,1215,85,RL,69.0,10205,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,134500

In [72]:
df["GarageType"].isnull().sum()

np.int64(81)

In [76]:
df["GarageType"].dtype

In [77]:
df["GarageType"].mode()[0]

'Attchd'

In [81]:
df["GarageType"].fillna(df["GarageType"].mode()[0],inplace=True)

C:\Users\PARAS\AppData\Local\Temp\ipykernel_24484\2964396816.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["GarageType"].fillna(df["GarageType"].mode()[0],inplace=True)

0       Attchd
1       Attchd
2       Attchd
3       Detchd
4       Attchd
         ...
1455    Attchd
1456    Attchd
1457    Attchd
1458    Attchd
1459    Attchd
Name: GarageType, Length: 1460, dtype: str

In [82]:
df["GarageQual"].isnull().sum()

np.int64(81)

In [83]:
df["GarageQual"].dtype

In [84]:
df["GarageQual"].fillna("NA",inplace=True)

C:\Users\PARAS\AppData\Local\Temp\ipykernel_24484\2498703835.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["GarageQual"].fillna("NA",inplace=True)

0       TA
1       TA
2       TA
3       TA
4       TA
        ..
1455    TA
1456    TA
1457    TA
1458    TA
1459    TA
Name: GarageQual, Length: 1460, dtype: str