## Pandas:- It is a package provided by python to clearn data
#### Data Clearning Standard tearm is data wrangling

#### Data Cleaning -> Create New Column,Rename Column,Drop Column,Drop Rows

#### Pandas Have Two Most Important Concept 

#### 1. DataFrame
#### 2. Series

### DataFrame -> More Than One Column Having Column as well as Index
### Series -> Single Column Data

In [ ]:
x={"Name":["Paras","Lalit","Vickey"],"Age":[20,50,90],"Cource":["DA","DS","DS"]}
print(x)

{'Name': ['Paras', 'Lalit', 'Vickey'], 'Age': [20, 50, 90], 'Cource': ['DA', 'DS', 'DS']}

In [ ]:
import pandas as pd

In [ ]:
d1=pd.DataFrame(x)

In [ ]:
d1

     Name  Age Cource
0   Paras   20     DA
1   Lalit   50     DS
2  Vickey   90     DS

In [ ]:
d1.to_csv("data.csv")

In [ ]:
# add new column 

d1["Palcement"]=["18 LPA","19 LPA","1 LPA"]
d1

     Name  Age Cource Palcement
0   Paras   20     DA    18 LPA
1   Lalit   50     DS    19 LPA
2  Vickey   90     DS     1 LPA

### 1) if same key passed the value got update 
### 2) if diffrent key passed then value got added in dictionary

In [ ]:
x={"Name":"Vivek"}
x

{'Name': 'Vivek'}

In [ ]:
x["city"]="Agra"
x

{'Name': 'Vivek', 'city': 'Agra'}

In [ ]:
d1["City"]=["New Delhi","New Delhi","Nodia"]
d1

     Name  Age Cource Palcement       City
0   Paras   20     DA    18 LPA  New Delhi
1   Lalit   50     DS    19 LPA  New Delhi
2  Vickey   90     DS     1 LPA      Nodia

In [ ]:
d1[["Name","Age","Cource","City","Palcement"]]

     Name  Age Cource       City Palcement
0   Paras   20     DA  New Delhi    18 LPA
1   Lalit   50     DS  New Delhi    19 LPA
2  Vickey   90     DS      Nodia     1 LPA

In [ ]:
# Rename Column 

d1.rename(columns={"City":"Citys"})

     Name  Age Cource Palcement      Citys
0   Paras   20     DA    18 LPA  New Delhi
1   Lalit   50     DS    19 LPA  New Delhi
2  Vickey   90     DS     1 LPA      Nodia

In [ ]:
d1

     Name  Age Cource Palcement       City
0   Paras   20     DA    18 LPA  New Delhi
1   Lalit   50     DS    19 LPA  New Delhi
2  Vickey   90     DS     1 LPA      Nodia

In [ ]:
# Rename Column Store 
# inplace -> True used for retaining the changes.

d1.rename(columns={"City":"Citys"},inplace=True)

In [ ]:
d1.rename(columns={"Cource":"Student_Cource"})

     Name  Age Student_Cource Palcement      Citys
0   Paras   20             DA    18 LPA  New Delhi
1   Lalit   50             DS    19 LPA  New Delhi
2  Vickey   90             DS     1 LPA      Nodia

In [ ]:
d1["Student_Cource"]=["DA","DS","DS"]

In [ ]:
d1

     Name  Age Cource Palcement      Citys Student_Cource
0   Paras   20     DA    18 LPA  New Delhi             DA
1   Lalit   50     DS    19 LPA  New Delhi             DS
2  Vickey   90     DS     1 LPA      Nodia             DS

In [ ]:
d1.rename({"City":"Stu_City"},axis=1,inplace=True)

In [ ]:
d1

     Name  Age Cource Palcement      Citys Student_Cource
0   Paras   20     DA    18 LPA  New Delhi             DA
1   Lalit   50     DS    19 LPA  New Delhi             DS
2  Vickey   90     DS     1 LPA      Nodia             DS

In [ ]:
d1.drop(columns=["Student_Cource"], inplace=True)
d1

     Name  Age Cource Palcement      Citys
0   Paras   20     DA    18 LPA  New Delhi
1   Lalit   50     DS    19 LPA  New Delhi
2  Vickey   90     DS     1 LPA      Nodia

In [ ]:
d1["stu_id"]=[101,102,103]

In [ ]:
d1

     Name  Age Cource Palcement      Citys  stu_id
0   Paras   20     DA    18 LPA  New Delhi     101
1   Lalit   50     DS    19 LPA  New Delhi     102
2  Vickey   90     DS     1 LPA      Nodia     103

In [ ]:
d1.set_index("stu_id",inplace=True)

In [ ]:
d1

          Name  Age Cource Palcement      Citys
stu_id
101      Paras   20     DA    18 LPA  New Delhi
102      Lalit   50     DS    19 LPA  New Delhi
103     Vickey   90     DS     1 LPA      Nodia

In [ ]:
d1.reset_index(inplace=True)
d1

   stu_id    Name  Age Cource Palcement      Citys
0     101   Paras   20     DA    18 LPA  New Delhi
1     102   Lalit   50     DS    19 LPA  New Delhi
2     103  Vickey   90     DS     1 LPA      Nodia

In [1]:
# d1.drop(columns=["index"], inplace=True)
# d1

In [ ]:
# Upload The File CSV File.

import pandas as pd

In [ ]:
df=pd.read_csv("titanic_train.csv")

In [ ]:
# head() -> Prints the first five top columns

df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# tail() -> Prints The Last bottom Five Colums

df.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# Shape() -> Shape returns numbers of rows and column.

df.shape

(891, 12)

In [ ]:
# info() -> Logica Structure of data

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [ ]:
df.isnull().sum() #Count of emapty cells in each column.

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df.isna().sum() # both are same isna and isnull.

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
x=[12,23,34,45,56,67,78,89,98,7,6,5,4]

# :
# [2:9] -> 2 3 4 5 6 7 8
# [:9] -> 0 1 2 3 4 5 6 7 8
# [2:] -> 2 3 4 5 6 7 8 .... till end of the list
# [:] -> from begining to end of list

In [ ]:
print(x[2:9])
print(x[:9])
print(x[2:])
print(x[:])

[34, 45, 56, 67, 78, 89, 98]
[12, 23, 34, 45, 56, 67, 78, 89, 98]
[34, 45, 56, 67, 78, 89, 98, 7, 6, 5, 4]
[12, 23, 34, 45, 56, 67, 78, 89, 98, 7, 6, 5, 4]

In [ ]:
#iloc and loc
#iloc --- index based slection
#df.iloc[:,:]

In [ ]:
df.iloc[0:5,:]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.iloc[0:5,4:7]

      Sex   Age  SibSp
0    male  22.0      1
1  female  38.0      1
2  female  26.0      0
3  female  35.0      1
4    male  35.0      0

### Extract only rows from 20-30 and column 3-8.

In [ ]:
df.iloc[19:30,2:8]

,Pclass,Name,Sex,Age,SibSp,Parch
19,3,"Masselmani, Mrs. Fatima",female,NaN,0,0
20,2,"Fynney, Mr. Joseph J",male,35.0,0,0
21,2,"Beesley, Mr. Lawrence",male,34.0,0,0
22,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0
23,1,"Sloper, Mr. William Thompson",male,28.0,0,0
24,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1
25,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5
26,3,"Emir, Mr. Farred Chehab",male,NaN,0,0
27,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2
28,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0
29,3,"Todoroff, Mr. Lalio",male,NaN,0,0

In [ ]:
#loc --- Lablel Based Selection
df.loc[0:5,:]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [ ]:
df.loc[0:5,"Name":"Fare"]

,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500
5,"Moran, Mr. James",male,NaN,0,0,330877,8.4583